version: '3'

tasks:
  lint:
    cmds:
      - cargo clippy --all-targets -- -D warnings
      - cargo fmt --check

  test:
    cmds:
      - cargo test

  check:
    cmds:
      - task: test
      - task: lint

  fix:
    cmds:
      - cargo clippy --fix --allow-staged

  fmt:
    cmds:
      - cargo fmt
