version: '3'

tasks:
  test:
    cmds:
      - cargo test

  test.timed:
    cmds:
      - rustup default nightly
      - defer: rustup default stable
      - cargo test --release -- -Z unstable-options --report-time  --test-threads 1

  check.fmt:
    cmds:
      - cargo fmt --check

  fix.fmt:
    cmds:
      - cargo fmt

  check.clippy:
    cmds:
      - cargo clippy --all-targets -- -D warnings

  fix.clippy:
    cmds:
      - cargo clippy --fix --allow-staged

  check:
    cmds:
      - task: test
      - task: check.clippy
      - task: check.fmt

  fix:
    cmds:
      - task: fix.clippy
      - task: fix.fmt
