version: '3'

tasks:
  test:
    cmds:
      - cargo test {{ empty .RELEASE | ternary "" "--release" }}

  lint:
    cmds:
      - cargo clippy --all-targets -- -D warnings
      - cargo fmt --check

  check:
    cmds:
      - task: test
      - task: lint

  fix:
    cmds:
      - cargo clippy --fix --allow-staged
      - task: fmt

  fmt:
    cmds:
      - cargo fmt
