version: "3"

tasks:
  check:
    cmds:
      - task: test
      - task: lint

  test:
    cmds:
      - cargo test

  lint:
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings
      - cargo fmt --check

  fix:
    cmds:
      - cargo clippy --all-targets --all-features --fix --allow-staged
      - cargo fmt
