version: '3'

tasks:
  lint:
    cmds:
      - poetry run black --check .
      - poetry run mypy .
      - npx prettier --check ./**/*.ts

  test:
    cmds:
      - poetry run pytest {{.CLI_ARGS}}
      - npx jest

  check:
    cmds:
      - task: lint
      - task: test

  fmt:
    cmds:
      - poetry run black .
      - npx prettier --write ./**/*.ts
