version: '3'

tasks:
  lint:
    cmds:
      - poetry run black --check .
      - poetry run mypy .

  test:
    cmds:
      - poetry run pytest {{.CLI_ARGS}}

  check:
    cmds:
      - task: lint
      - task: test

  fmt:
    cmds:
      - poetry run black .
