require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false