# frozen_string_literal: true

require 'minitest/test_task'
require 'rubocop/rake_task'

task default: %w[test lint]

Minitest::TestTask.create(:test) do |t|
  t.libs << 'test'
  t.libs << 'lib'
  t.warning = false
  t.test_globs = ['day*/*_test.rb']
end

RuboCop::RakeTask.new(:lint) do |task|
  task.patterns = ['day*/*.rb']
  task.fail_on_error = false
end
