name: CI 2015 Rust
on:
  push:
    branches:
      - master
      - '2015-rs-*'
    paths:
      - '2015/rust/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Check
        run: task check
        working-directory: ./2015/rust/aoc