name: CI 2022 Typescript
on:
  push:
    branches:
      - master
      - "2022-ts-*"
jobs:
  check-code:
    name: Check the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Install JS/TS dependencies
        run: npm install
        working-directory: ./2022/typescript
      - name: Check
        run: task check
        working-directory: ./2022/typescript
