name: CI 2020 Go
on:
  push:
    branches:
      - master
      - '2020-go-*'
    paths:
      - '2020/go/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/checkout@v3
      - run: go test ./...
        working-directory: ./2020/go