name: CI 2020
on:
  push:
    branches:
      - master
      - '2020-*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.15.0'
      - uses: actions/checkout@v2
      - run: cd 2020 && go test ./...