name: CI 2022
on:
  push:
    branches:
      - master
      - '2022-*'
jobs:
  check-code:
    name: Check the code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install taskfile
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python -
      - name: Install dependencies
        run: poetry install
        working-directory: ./2022
      - name: Check
        run: task check
        working-directory: ./2022
